import * as React from "react";
import Box from "@material-ui/core/Box";
import CssBaseline from "@material-ui/core/CssBaseline";
import BottomNavigation from "@material-ui/core/BottomNavigation";
import BottomNavigationAction from "@material-ui/core/BottomNavigationAction";
import FavoriteIcon from "@material-ui/icons/Favorite";
import ArchiveIcon from "@material-ui/icons/Archive";
import Paper from "@material-ui/core/Paper";
import { IoHomeOutline, IoNotificationsOutline } from "react-icons/io5";
import "./MViewNav.scss";
import {
  FiActivity,
  FiFilePlus,
  FiMessageCircle,
  FiUsers,
} from "react-icons/fi";
import { NavLink } from "react-router-dom";

export default function MobileViewNav() {
  const [value, setValue] = React.useState(0);
  const ref = React.useRef(null);

  return (
    <Box sx={{ pb: 7 }} ref={ref}>
      <CssBaseline />

      <Paper elevation={3} className="paper__paper">
        <BottomNavigation
          showLabels
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        >
          <NavLink100
            to="/slate"
            exact
            className="NavLink100"
            activeClassName="active-nav"
          >
            <BottomNavigationAction
              label="Home"
              icon={<IoHomeOutline />}
              className="b_n_a"
            />
          </NavLink100>
          <BottomNavigationAction label="Activity" icon={<FiActivity />} />
          <BottomNavigationAction label="Group" icon={<FiUsers />} />
          <BottomNavigationAction label="Archive" icon={<ArchiveIcon />} />
        </BottomNavigation>
      </Paper>
    </Box>
  );
}

// const messageExamples = [
//   {
//     primary: "Brunch this week?",
//     secondary:
//       "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     person: "/static/images/avatar/5.jpg",
//   },
//   {
//     primary: "Birthday Gift",
//     secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     person: "/static/images/avatar/1.jpg",
//   },
//   {
//     primary: "Recipe to try",
//     secondary:
//       "I am try out this new BBQ recipe, I think this might be amazing",
//     person: "/static/images/avatar/2.jpg",
//   },
//   {
//     primary: "Yes!",
//     secondary: "I have the tickets to the ReactConf for this year.",
//     person: "/static/images/avatar/3.jpg",
//   },
//   {
//     primary: "Doctor's Appointment",
//     secondary:
//       "My appointment for the doctor was rescheduled for next Saturday.",
//     person: "/static/images/avatar/4.jpg",
//   },
//   {
//     primary: "Discussion",
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: "/static/images/avatar/5.jpg",
//   },
//   {
//     primary: "Summer BBQ",
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: "/static/images/avatar/1.jpg",
//   },
// ];
